### PR TITLE
Check for added or removed outputs before setting temperature

### LINKED ISSUE #3: Watch for new outputs
The daemon only sets the color for outputs that were presented on the startup: if I start the daemon, then connect a new display and then try to modify the color, newly connected display is unaffected.

### PR DESCRIPTION
**Pull request by jeremija**
Hey @MaxVerevkin,

I think I have something working. The trick is to call `wl_display_roundtrip` to execute all pending events, then all the callbacks will be executed synchronously.

The current implementation will check for any new outputs on every call to `wl_gammarelay_color_set` and initialize the gamma for those.

Ideally this would happen automatically, but that requires some more careful considerations because we'd have to access the state from different threads and that could cause race conditions, so I'm not sure if I have time to implement it at this point.

Would be great if you could test and see if this works for you!

Cheers!

Closes #3.

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
> Would be great if you could test and see if this works for you!

It works most of the time, but sometimes, If I start changing the temperature right after I enable my second output, I get the following: `output does not have ramp_size set` and it doesn't fix itself until I reconnect my display.

> Ideally this would happen automatically, but that requires some more careful considerations because we'd have to access the state from different threads and that could cause race conditions, so I'm not sure if I have time to implement it at this point.

Speaking of race conditions: I've got a working prototype written entirely in rust! Internally it spawns a thread that processes wayland stuff and at the same time checks a channel for new temperature requests. This thread "remembers" the temperature and when a new output is found it sets the temperature immediately.

**Comment by jeremija** [comment]
> Internally it spawns a thread that processes wayland stuff and at the same time checks a channel for new temperature requests. 

Cool, do you use a timer? If not, I'm curious how do you unblock the event loop to process the requests in that thread?

Maybe there's a way to schedule execution of custom functions in that event loop.

**Comment by jeremija** [comment]
Also, can have you tried the second last commit? I just pushed some changes that free resources, but that might've messed something up.

**Comment by MaxVerevkin** [comment]
> Cool, do you use a timer? If not, I'm curious how do you unblock the event loop to process the requests in that thread?

I used a nonblocking equivalent of `blockig_dispatch()` for the Wayland and non blocking `Receiver::try_recv()` for the channel. And `sleep_ms(10)` at the end of the loop...

However I have the FD of the underlying connection socket, so there must be a way to integrate it  into `tokio` or whatever. If I manage to do so, I will be able to get rid of the thread and use async rust instead.

> Also, can have you tried the second last commit?

I will when I get to my laptop.

**Comment by jeremija** [comment]
Thanks, last night I did some reading as well and I think I came to a similar conclusion: use a `fd` and then use the `poll` syscall that writes to a channel in combination with:

```c
wl_display_dispatch_pending(display);
wl_display_flush(display);
```

in the main event loop that is triggered on every response from `poll`. So I don't have to use a timer at all!

I also added a check for number of initialized outputs, and if that number changes the temperature will be reset with the last value:

```
2022/01/25 10:01:05 Number of outputs: 1
{"updates":[{"key":"color","color":{"temperature":"2000","brightness":"1.00"}}]}
poll result: 1
2022/01/25 10:01:10 poll ret 1
2022/01/25 10:01:10 poll goroutine done
starting poll: 3
poll result: 1
2022/01/25 10:01:10 poll ret 1
registry handle name: 48, interface: wl_output
got output name: 48, interface: wl_output
2022/01/25 10:01:10 handlePoll result 1
2022/01/25 10:01:10 Number of outputs: 1
2022/01/25 10:01:10 poll goroutine done
starting poll: 3
2022/01/25 10:01:10 handlePoll result 3
calling setColor 2 1
color_set starting for each
processing output
processing output
2022/01/25 10:01:10 Number of outputs: 2
```

The code is a mess right now, but it seems to work on my machine. Can you please test again?

There are two things I'm not sure how to handle yet:

1. The goroutine that calls `wl_gammarelay_poll` never seems to terminate
2. ~When I call `wl_display_disconnect` it panics. It seems to be related to `wl_display_get_fd`, because if I remove that part it works.~ D'oh I called `calloc` with the wrong size :facepalm:

**Comment by MaxVerevkin** [comment]
> Can you please test again?

New outputs still don't get their temperature set automatically :( (I'm not good at reading go code, so I'm not sure why)

Meanwhile I managed to integrate my prototype with `tokio` ([it was trivial](https://docs.rs/tokio/1.15.0/tokio/io/unix/struct.AsyncFd.html)), so now it runs on a single thread. I can post my code if you are interested.

**Comment by jeremija** [comment]
Can you post the log from the start and until you connect the output?

**Comment by MaxVerevkin** [comment]
Nothing was printed after I connected my display (I run `swaymsg output eDP-1 toggle`)
```
registry handle name: 1, interface: wl_shm
registry handle name: 2, interface: wl_drm
registry handle name: 3, interface: zwp_linux_dmabuf_v1
registry handle name: 4, interface: wl_compositor
registry handle name: 5, interface: wl_subcompositor
registry handle name: 6, interface: wl_data_device_manager
registry handle name: 7, interface: zwlr_gamma_control_manager_v1
registry handle name: 8, interface: zxdg_output_manager_v1
registry handle name: 9, interface: org_kde_kwin_idle
registry handle name: 10, interface: zwp_idle_inhibit_manager_v1
registry handle name: 11, interface: zwlr_layer_shell_v1
registry handle name: 12, interface: xdg_wm_base
registry handle name: 13, interface: zwp_tablet_manager_v2
registry handle name: 14, interface: org_kde_kwin_server_decoration_manager
registry handle name: 15, interface: zxdg_decoration_manager_v1
registry handle name: 16, interface: zwp_relative_pointer_manager_v1
registry handle name: 17, interface: zwp_pointer_constraints_v1
registry handle name: 18, interface: wp_presentation
registry handle name: 19, interface: zwlr_output_manager_v1
registry handle name: 20, interface: zwlr_output_power_manager_v1
registry handle name: 21, interface: zwp_input_method_manager_v2
registry handle name: 22, interface: zwp_text_input_manager_v3
registry handle name: 23, interface: zwlr_foreign_toplevel_manager_v1
registry handle name: 24, interface: zwlr_export_dmabuf_manager_v1
registry handle name: 25, interface: zwlr_screencopy_manager_v1
registry handle name: 26, interface: zwlr_data_control_manager_v1
registry handle name: 27, interface: zwp_primary_selection_device_manager_v1
registry handle name: 28, interface: wp_viewporter
registry handle name: 29, interface: zxdg_exporter_v1
registry handle name: 30, interface: zxdg_importer_v1
registry handle name: 31, interface: zxdg_exporter_v2
registry handle name: 32, interface: zxdg_importer_v2
registry handle name: 33, interface: zwp_virtual_keyboard_manager_v1
registry handle name: 34, interface: zwlr_virtual_pointer_manager_v1
registry handle name: 35, interface: zwlr_input_inhibit_manager_v1
registry handle name: 36, interface: zwp_keyboard_shortcuts_inhibit_manager_v1
registry handle name: 37, interface: wl_seat
registry handle name: 38, interface: zwp_pointer_gestures_v1
registry handle name: 40, interface: wl_output
got output name: 40, interface: wl_output
2022/01/25 16:32:08 Started daemon
2022/01/25 16:32:09 New connection. Active connections: 1
2022/01/25 16:32:09 Received request: {"subscribe":["color"]}
2022/01/25 16:32:09 Sending response: {"updates":[{"key":"color","color":{"temperature":"6500","brightness":"1.00"}}],"subscribed":["color"]}
2022/01/25 16:32:11 Received request: {"color":{"temperature":"6000"}}
color_set starting for each
processing output
2022/01/25 16:32:11 Sending response: {"color":{"temperature":"6000","brightness":"1.00"}}
2022/01/25 16:32:12 Received request: {"color":{"temperature":"5500"}}
color_set starting for each
processing output
2022/01/25 16:32:12 Sending response: {"color":{"temperature":"5500","brightness":"1.00"}}
2022/01/25 16:32:12 Received request: {"color":{"temperature":"5000"}}
color_set starting for each
processing output
2022/01/25 16:32:12 Sending response: {"color":{"temperature":"5000","brightness":"1.00"}}
2022/01/25 16:32:12 Received request: {"color":{"temperature":"4500"}}
color_set starting for each
processing output
2022/01/25 16:32:12 Sending response: {"color":{"temperature":"4500","brightness":"1.00"}}
2022/01/25 16:32:12 Received request: {"color":{"temperature":"4000"}}
color_set starting for each
processing output
2022/01/25 16:32:12 Sending response: {"color":{"temperature":"4000","brightness":"1.00"}}
2022/01/25 16:32:12 Received request: {"color":{"temperature":"3500"}}
color_set starting for each
processing output
2022/01/25 16:32:12 Sending response: {"color":{"temperature":"3500","brightness":"1.00"}}
2022/01/25 16:32:12 Received request: {"color":{"temperature":"3000"}}
color_set starting for each
processing output
2022/01/25 16:32:12 Sending response: {"color":{"temperature":"3000","brightness":"1.00"}}
2022/01/25 16:32:12 Received request: {"color":{"temperature":"2500"}}
color_set starting for each
processing output
2022/01/25 16:32:12 Sending response: {"color":{"temperature":"2500","brightness":"1.00"}}
^C2022/01/25 16:32:16 Terminating connection
2022/01/25 16:32:16 Failed to decode message: decoding request: read unix /run/user/1000/wl-gammarelay.sock->@: use of closed network connection
2022/01/25 16:32:16 Write error: setting write deadline: set unix /run/user/1000/wl-gammarelay.sock: use of closed network connection
2022/01/25 16:32:16 Connection closed. Active connections: 0
```

**Comment by jeremija** [comment]
Thanks, are you running the latest commit from this MR?

It should print `Number of outputs: 1` but I don't see it in your log.

**Comment by MaxVerevkin** [comment]
Oh, sorry, my local repo got messed up somehow (`git pull` didn't pull), I've cloned again and now it works.

Everything's good except for

> It works most of the time, but sometimes, If I start changing the temperature right after I enable my second output, I get the following: output does not have ramp_size set and it doesn't fix itself until I reconnect my display.

but I'm facing the same issue in my prototype as fell. Might be sway's issue?

**Comment by jeremija** [comment]
Oh cool, thanks for confirming and explaining. I'll test that sway command too, previously I was only connecting and disconnecting the display cable to test it.

**Comment by MaxVerevkin** [comment]
Also I think main thread gets blocked sometimes - right now for example it doesn't respond to any requests.

Edit: but when I toggle the output it processes the requests and blocks again.

**Comment by MaxVerevkin** [comment]
> Might be sway's issue?

No, I managed to resolve it in my code. In my case it was caused by not `release()`ing and `destroy()`ing properly.

**Comment by MaxVerevkin** [comment]
Here's my try which seems to work fine for me - https://github.com/MaxVerevkin/wl-gammarelay-rs

**Comment by jeremija** [comment]
@MaxVerevkin just I pushed another commit. I think I resolved the deadlock, can you please test it?

> Here's my try which seems to work fine for me - https://github.com/MaxVerevkin/wl-gammarelay-rs

Just took a look at your code, man that's tidy!

>  has three times less SLOC

Although I'm sure that the dependencies have many more :stuck_out_tongue: :slightly_smiling_face:

**Comment by MaxVerevkin** [comment]
> I just pushed another commit. I think I resolved the deadlock, can you please test it?

It works now, I couldn't even reproduce that problem when `ramp_size` was "lost". Awesome!

> Although I'm sure that the dependencies have many more

Perhaps :)

**Comment by jeremija** [comment]
Awesome, thanks for confirming! 😃🎉

**Pull request closed without merging**
